# Generated by Django 3.0.5 on 2020-04-11 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='cpompleted',
            new_name='completed',
        ),
    ]
